name: Crawl Subsidies
on:
  schedule: [ { cron: "5 * * * *" } ]
  workflow_dispatch: {}

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run incremental crawler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CONNECT_TIMEOUT: "12"
          READ_TIMEOUT: "45"
          CHUSHO_READ_TIMEOUT: "75"
          TIME_BUDGET_SEC: "480"
          MAX_PAGES_PER_RUN: "120"
          MAX_PER_DOMAIN: "50"
          # TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: python crawl_incremental.py
