name: Crawl Subsidies
on:
  workflow_dispatch: {}
  schedule: [ { cron: "5 * * * *" } ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run orchestrator
        env:
          # === 必須 Secrets ===
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VERTEX_SERVING_CONFIG: ${{ secrets.VERTEX_SERVING_CONFIG }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          # === Discovery の選択 ===
          # OpenAI Deep Research を使う: "1" / Vertex を使う: "0"
          USE_OPENAI_DR: "1"
          # Deep Research が探索してよいドメイン（カンマ区切り）
          DR_ALLOWED_DOMAINS: "www.chusho.meti.go.jp,chusho.meti.go.jp,www.meti.go.jp,meti.go.jp,www.jgrants-portal.go.jp,jgrants-portal.go.jp"
          # モデル/タイムアウト（お好みで）
          DR_MODEL: "o4-mini-deep-research-2025-06-26"
          DR_TIMEOUT_SEC: "40"

          # === 月次の上限（無料枠ガード） ===
          VERTEX_Q_MONTH_LIMIT: "9000"
          VERTEX_Q_PER_RUN: "50"
          OPENAI_Q_MONTH_LIMIT: "9000"   # ← OpenAI 版の月次上限（まずはVertexと同値でOK）
          OPENAI_Q_PER_RUN: "1"          # ← 1回のRunで Deep Research API を何回まで叩くか（1推奨）

          # === ウォッチドッグ（10分） ===
          HARD_KILL_SEC: "600"

          # === 速攻寄り（crawl に 4分回す設定） ===
          CONNECT_TIMEOUT: "8"
          READ_TIMEOUT: "30"
          CHUSHO_READ_TIMEOUT: "45"
          TIME_BUDGET_SEC: "240"
          MAX_PAGES_PER_RUN: "60"
          MAX_PER_DOMAIN: "20"
          PARALLEL_WORKERS: "6"
          PER_HOST_LIMIT: "2"

          RUN_ID: ${{ github.run_id }}
        run: python orchestrator.py
