name: Crawl Serial (one-by-one)

on:
  schedule:
    # 5分おき（UTC）。JSTで日中だけにしたい場合は 0-8, 0-14 等に調整してください
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

concurrency:
  group: crawl-serial
  cancel-in-progress: true

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run orchestrator (serial one-by-one)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VERTEX_SERVING_CONFIG: ${{ secrets.VERTEX_SERVING_CONFIG }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          # シリアル処理モードを有効化（1件だけ処理・crawl/discoveryはスキップ）
          SINGLE_BACKFILL_ONE: "1"

          # タイムアウトは保険（1件なので既定のままでOK）
          HARD_KILL_SEC: "600"
          READ_TIMEOUT: "60"
          CHUSHO_READ_TIMEOUT: "90"

          RUN_ID: ${{ github.run_id }}
        run: python orchestrator.py
