name: Crawl Subsidies
on:
  workflow_dispatch: {}
  schedule: [ { cron: "5 * * * *" } ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 12            # ← ジョブ全体の上限（12分で強制終了）

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run orchestrator
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          # Vertex discovery
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VERTEX_SERVING_CONFIG: ${{ secrets.VERTEX_SERVING_CONFIG }}

          # 無料枠ガード（例：月9000 / 1run=50）
          VERTEX_Q_MONTH_LIMIT: "9000"
          VERTEX_Q_PER_RUN: "50"

          # ★ ウォッチドッグ：10分を越えたら必ず main() を抜ける
          HARD_KILL_SEC: "600"

          # 速攻モード（3分で増やす）
          CONNECT_TIMEOUT: "8"
          READ_TIMEOUT: "25"
          CHUSHO_READ_TIMEOUT: "35"
          TIME_BUDGET_SEC: "180"
          MAX_PAGES_PER_RUN: "60"
          MAX_PER_DOMAIN: "20"
          PARALLEL_WORKERS: "6"
          PER_HOST_LIMIT: "2"

          RUN_ID: ${{ github.run_id }}
        run: python orchestrator.py
