name: Crawl Serial (one-by-one)

on:
  schedule:
    - cron: "*/5 * * * *"     # 5分おき（UTC）
  workflow_dispatch: {}

concurrency:
  group: crawl-serial
  cancel-in-progress: true

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run orchestrator (serial one-by-one)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          VERTEX_SERVING_CONFIG: ${{ secrets.VERTEX_SERVING_CONFIG }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          # ---- シリアルで1件ずつ ----
          SINGLE_BACKFILL_ONE: "1"
          SINGLE_MAX_TRY: "2"               # ← 5 → 2（最大2件までに制限）

          # ---- 3分でDR切替（Stage1）----
          SINGLE_STAGE1_READ_TIMEOUT: "180" # = 3分

          # ---- 接続失敗対策 ----
          SINGLE_FORCE_CONNECT_TIMEOUT: "30"
          DR_FETCH_ON_SERIAL: "1"

          # ---- HEADプリフライト ----
          HEAD_CONNECT_TIMEOUT: "8"
          HEAD_READ_TIMEOUT: "6"
          SINGLE_LARGE_BYTES: "8000000"     # 8MB以上はDRへ

          # ---- 安全装置（12分上限に収める）----
          HARD_KILL_SEC: "600"
          CONNECT_TIMEOUT: "8"
          READ_TIMEOUT: "60"

          RUN_ID: ${{ github.run_id }}
        run: python orchestrator.py
