name: Crawl Subsidies
on:
  schedule: [ { cron: "5 * * * *" } ]
  workflow_dispatch: {}
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: python -m pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - name: Run incremental crawler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FORCE_REFRESH: "1"          # ← ★ この行を一時追加（1回だけON）
          CONNECT_TIMEOUT: "10"
          READ_TIMEOUT: "35"
          CHUSHO_READ_TIMEOUT: "45"
        run: python crawl_incremental.py
