name: Prune DB
on:
  schedule: [ { cron: "30 2 * * *" } ]
  workflow_dispatch: {}
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip
      - run: pip install "psycopg[binary]>=3.1.18,<3.3"
      - name: Apply schema
        env: { DATABASE_URL: ${{ secrets.DATABASE_URL }} }
        run: |
          python - <<'PY'
          import os, psycopg, pathlib
          dsn=os.getenv("DATABASE_URL")
          with psycopg.connect(dsn, autocommit=True) as c:
              c.execute(pathlib.Path("schema.sql").read_text())
          print("schema applied")
          PY
